import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner';
import Cards from '../components/Cards';
import Footer from '../components/Footer';
import MainInfo from '../components/MainInfo';
import Navbarr from './../components/Navbarr';




export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main >

        <Banner />
        <MainInfo />
        <Cards />
        <Footer />
      </main>
    </div>)
}
